global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-consumer'
    static_configs:
      - targets: ['node-consumer:9090']

  - job_name: 'tidb'
    static_configs:
      - targets: ['tidb:10080']

  - job_name: 'tikv'
    static_configs:
      - targets: ['tikv:20180']

  - job_name: 'pd'
    static_configs:
      - targets: ['pd:2379']

  - job_name: 'ticdc'
    static_configs:
      - targets: ['ticdc:8300']
